
spring:
  application:
    name: service-config
  profiles:
    active: native

server:
  port:
    7000
    
management:
  context-path: /admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:7777/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
