
spring:
  application:
    name: sps-eureka-service
  output:
    ansi:
      enabled: always

server:
  port: 7777

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-expiration-duration-in-seconds: 10
    non-secure-port: 7777
    lease-renewal-interval-in-seconds: 5
